require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - '^# [^\n]+'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - on
    - os
    - pp
    - to

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  AllowedMethods:
    - increment!
    - decrement!
    - touch

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/RedundantFetchBlock:
  Safe: true
